import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Background from "@/components/Background/Background";

// Configure the font
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased text-gray-400 text-xs font-inter`}>
        <Background color="#456DFF" />
        {children}
      </body>
    </html>
  );
}
